/** @type {import('tailwindcss').Config} */
module.exports = {
    darkMode: ["class"],
    content: ["./src/**/*.{js,jsx,ts,tsx}", "./public/index.html"],
    theme: {
        extend: {
            fontFamily: {
                serif: ['"Cormorant Garamond"', "serif"],
                sans: ['"Manrope"', "ui-sans-serif", "system-ui"],
            },
            colors: {
                bloom: {
                    cream: "#F5EFE5",
                    "cream-muted": "#EFE9DF",
                    paper: "#FFFFFF",
                    cocoa: "#4A3A28",
                    "cocoa-hover": "#3D2F20",
                    sage: "#8A9A86",
                    "sage-hover": "#788774",
                    rose: "#D4B8B1",
                    "rose-hover": "#C5A59D",
                    text: "#4A3A28",
                    text2: "#6A5D4D",
                    muted: "#968B7D",
                    border: "#E2D9CB",
                },
                background: "hsl(var(--background))",
                foreground: "hsl(var(--foreground))",
                card: { DEFAULT: "hsl(var(--card))", foreground: "hsl(var(--card-foreground))" },
                popover: { DEFAULT: "hsl(var(--popover))", foreground: "hsl(var(--popover-foreground))" },
                primary: { DEFAULT: "hsl(var(--primary))", foreground: "hsl(var(--primary-foreground))" },
                secondary: { DEFAULT: "hsl(var(--secondary))", foreground: "hsl(var(--secondary-foreground))" },
                muted: { DEFAULT: "hsl(var(--muted))", foreground: "hsl(var(--muted-foreground))" },
                accent: { DEFAULT: "hsl(var(--accent))", foreground: "hsl(var(--accent-foreground))" },
                destructive: { DEFAULT: "hsl(var(--destructive))", foreground: "hsl(var(--destructive-foreground))" },
                border: "hsl(var(--border))",
                input: "hsl(var(--input))",
                ring: "hsl(var(--ring))",
            },
            borderRadius: {
                lg: "var(--radius)",
                md: "calc(var(--radius) - 2px)",
                sm: "calc(var(--radius) - 4px)",
                "3xl": "1.75rem",
                "4xl": "2.5rem",
            },
            keyframes: {
                "accordion-down": { from: { height: "0" }, to: { height: "var(--radix-accordion-content-height)" } },
                "accordion-up": { from: { height: "var(--radix-accordion-content-height)" }, to: { height: "0" } },
                "fade-up": { "0%": { opacity: "0", transform: "translateY(20px)" }, "100%": { opacity: "1", transform: "translateY(0)" } },
            },
            animation: {
                "accordion-down": "accordion-down 0.2s ease-out",
                "accordion-up": "accordion-up 0.2s ease-out",
                "fade-up": "fade-up 0.8s cubic-bezier(0.25, 1, 0.5, 1)",
            },
        },
    },
    plugins: [require("tailwindcss-animate")],
};
